# Generated by Django 3.2.10 on 2022-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'not specified'), (1, 'male'), (2, 'female')], default=0),
        ),
    ]
